name: lofi
channels:
  - bioconda
  - conda-forge
dependencies:
  - bakta=1.11.0
  - ncbi-amrfinderplus
  - parallel
  - python=3.11
  - pip=25.1
  - snakemake=7.32.4
  - diamond==2.1
  - pip:
      - bcbio-gff==0.7.1
      - biopython==1.85
      - gdown==5.2.0
      - hmmlearn==0.3.3
      - lightgbm==4.5.0
      - wget==3.2